import Head from 'next/head'
import { Header } from '@/components/Header'
import { api } from '@/lib/axios'
import { GetServerSideProps } from 'next'
import { Products } from '@/components/Products'
import { Footer } from '@/components/Footer'

export interface IProduct {
  id: number
  name: string
  brand: string
  description: string
  photo: string
  price: string
}

interface HomeProps {
  data: {
    products: IProduct[]
  }
}

export default function Home({ data }: HomeProps) {
  console.log(data.products)

  return (
    <>
      <Head>
        <title>MKS Sistemas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Products products={data.products} />
      <Footer />
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  try {
    const response = await api.get('/products?page=1&rows=50&sortBy=id&orderBy=ASC');
    const data = response.data;

    return {
      props: {
        data,
      },
    };
  } catch (error) {
    console.error('Error fetching products:', error);
    return {
      props: {
        products: [],
      },
    };
  }
}